version: '2'
services:
    twentyonepoints-app:
        image: twentyonepoints
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://twentyonepoints-mysql:3306/twentyonepoints?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=twentyonepoints-elasticsearch:9300
        ports:
            - 8080:8080
    twentyonepoints-mysql:
        extends:
            file: mysql.yml
            service: twentyonepoints-mysql
    twentyonepoints-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: twentyonepoints-elasticsearch
